version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "quart-app"
      POSTGRES_USER: "psql_user"
      POSTGRES_PASSWORD: "1"
    volumes:
      - postgres-data:/psql_data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
